### ISSUE TITLE
Simple optimizatoion

### ISSUE THREAD

**Issue by PharmCat** [AhmedSalih3d/SPHExample#5]
Thank you for previous reaction on issues, now it work fine! 

https://github.com/AhmedSalih3d/SPHExample/blob/414bf2adcb13b20abce9453b1f73acdbc7b1c909/src/SimulationEquations.jl#L22

I think you can simple change 

```
for (iter,L) in collect(enumerate(list))
```

to 

```
for (iter,L) in enumerate(list)
```

and

https://github.com/AhmedSalih3d/SPHExample/blob/414bf2adcb13b20abce9453b1f73acdbc7b1c909/src/TimeStepping.jl#L10C9-L10C82

and something like this 

```
 visc  = maximum(abs.(h* dot.(v,points) ./ (dot.(points,points) .+ eta2)))
```

to

```
 visc  = maximum(@. abs(h * dot(v, points) / (dot(points, points) + eta2)))
```
and it may be more readable with better performance

also advice use ProgressMeter:

```
import ProgressMeter: @showprogress

# ...

@showprogress for sim_iter = 1:NumberOfIterations

# ...
```

**Comment by AhmedSalih3d** [comment]
Hello @PharmCat !

No worries, I really enjoy getting feedback 😊

I am improving the whole structure of the package and making it even easier to use, while keeping it elegant and relatively simple (I hope). The work is going on in this branch:

https://github.com/AhmedSalih3d/SPHExample/tree/optimize-code-execution

Some of the changes are based on @lmiq (Julia Discourse) feedback.

And I have implemented all three of your suggestions!

Could you kindly help me with one thing though; do you happen to know how I can change the print statement?

![image](https://github.com/AhmedSalih3d/SPHExample/assets/36305327/ebba9bf3-998d-4344-b75b-cbb0aaa6cd94)

I would like it to at the right end to say: "Total Simulation Time: x " somewhere, do you know how?

**Comment by PharmCat** [comment]
> I would like it to at the right end to say: "Total Simulation Time: x " somewhere, do you know how?

I think this example can be useful:

```
x,n = 1,10
p = Progress(n)
for iter in 1:10
    x *= 2
    sleep(0.5)
    next!(p; showvalues = [(:iter,iter), (:x,x)])
end
```

My approach:

```
import ProgressMeter: @showprogress, next!, Progress, BarGlyphs

# ...

progr = Progress(NumberOfIterations,
        dt=1.0,
        barglyphs=BarGlyphs('|','█', ['▁' ,'▂' ,'▃' ,'▄' ,'▅' ,'▆', '▇'],' ','|',),
        showspeed=true
    )

# ...

next!(progr; showvalues = [(:iter, sim_iter), (:dt, dt)])

```

**Comment by AhmedSalih3d** [comment]
Amazing!

I had not spotted the `showvalues` keyword, but it really does exactly what I want:

![image](https://github.com/AhmedSalih3d/SPHExample/assets/36305327/12776f6f-5c44-4685-a3e8-f6589521e6c4)

This looks so cool to me! At a later stage, I aim to make this part of the new SimulationMetaData struct, in the sense that one can specific the "Progress" variable how one would want, while it has some defaults and formatting I will fix later.

I close this issue now, since all topics have been addressed (other than the visual of the loading bar! 😁)

Any future suggestions/issues, please keep them coming they are so helpful. Perhaps you could give (no expectations, you have already helped so much)

https://github.com/AhmedSalih3d/SPHExample/tree/optimize-code-execution

A spin, it seems to work well for me with the added features and simplified interface/code structure.

 Kind regards
